spring.application.name=booking-project

server.port=8088

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5433/booking}
spring.datasource.username=${DB_USERNAME:booking}
spring.datasource.password=${DB_PASSWORD:booking}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true